name: Deploy on Push

on:
  push:
    branches:
      - deploycode_using_fastapi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call deployment API
        run: |
          curl -X POST \
            -H "X-API-Token: ${{ secrets.API_TOKEN }}" \
            https://getcode.bibhtech.shop/deploy
