name: Build and Push Docker Image & Update ArgoCD

on:
  push:
    branches:
      - scan-trivy

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app source repo
        uses: actions/checkout@v2

      - name: Generate random tag
        id: random
        run: echo "tag=$(uuidgen | cut -d'-' -f1)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t azuresubha/092024:${{ steps.random.outputs.tag }} .

      - name: Push Docker image
        run: |
          docker push azuresubha/092024:${{ steps.random.outputs.tag }}

      - name: Clone ArgoCD config repo using custom credentials
        run: |
          git clone --branch test-argocd-config https://${{ secrets.USER_GIT }}:${{ secrets.PASSWORD_GIT }}@github.com/subha4256/argocd-config.git
          cd argocd-config

          # Update deploy.yml with new image tag
          sed -i "s|azuresubha/092024:.*|azuresubha/092024:${{ steps.random.outputs.tag }}|g" deploy.yml

          git config user.name "${{ secrets.USER_GIT }}"
          git config user.email "${{ secrets.USER_GIT }}@users.noreply.github.com"

          git add deploy.yml
          git commit -m "Update image tag to azuresubha/092024:${{ steps.random.outputs.tag }}"
          git push origin test-argocd-config
