name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t azuresubha/092024:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push azuresubha/092024:${{ github.sha }}

      - name: Tag latest image
        run: |
          docker tag azuresubha/092024:${{ github.sha }} azuresubha/092024:latest
          docker push azuresubha/092024:latest
